/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import java.awt.Graphics;
import java.util.Random;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author ADM
 */
public class Jogo12 extends javax.swing.JFrame {

    /**
     * Creates new form Jogo1
     */
    public Jogo12() {
        initComponents();

        setSize(1020, 620);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
        setLayout(null);

        // Criando o JPanel com imagem de fundo
        JPanel P = new JPanel() {
            @Override
            protected void paintComponent(Graphics g) {
//                super.paintComponent(g);
//                ImageIcon imagemPanel = new ImageIcon("C:\\Users\\dev\\Documents\\NetBeansProjects\\Swing - NPC Revoltado\\src\\Resource\\Menu Iniciar.png");
//                g.drawImage(imagemPanel.getImage(), 0, 0, getWidth(), getHeight(), null);
            }
        };
        P.setBounds(500, 500, 1020, 620); // Define posição e tamanho
        P.setOpaque(false); // Torna o painel transparente
        P.setLayout(null); // Define layout absoluto no painel

        // Adiciona o painel ao JFrame
        getContentPane().add(P);

        // Configurando o fundo
        ImageIcon imagemBackground = new ImageIcon("C:\\Users\\ADM\\Documents\\NetBeansProjects\\ProjetoIntegrador\\src\\Imagens\\Acampamento.png");
        JLabel labelBackground = new JLabel(imagemBackground);
        labelBackground.setBounds(0, 0, 1020, 620);

        // Adiciona o fundo como último elemento
        getContentPane().add(labelBackground);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Vasculhar_bau = new javax.swing.JButton();
        Vasculhar_Tenda = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Vasculhar_bau.setBackground(new java.awt.Color(204, 204, 204));
        Vasculhar_bau.setFont(new java.awt.Font("Blackadder ITC", 0, 24)); // NOI18N
        Vasculhar_bau.setForeground(new java.awt.Color(0, 0, 0));
        Vasculhar_bau.setText("Vasculhar bau Suspeito");
        Vasculhar_bau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Vasculhar_bauActionPerformed(evt);
            }
        });

        Vasculhar_Tenda.setBackground(new java.awt.Color(204, 204, 204));
        Vasculhar_Tenda.setFont(new java.awt.Font("Blackadder ITC", 0, 24)); // NOI18N
        Vasculhar_Tenda.setForeground(new java.awt.Color(0, 0, 0));
        Vasculhar_Tenda.setText("Vasculhar tenda");
        Vasculhar_Tenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Vasculhar_TendaActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Blackadder ITC", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("O que você quer fazer");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(214, 214, 214)
                .addComponent(Vasculhar_Tenda)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(426, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Vasculhar_bau)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(315, 315, 315))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(jLabel2)
                .addGap(131, 131, 131)
                .addComponent(Vasculhar_Tenda)
                .addGap(54, 54, 54)
                .addComponent(Vasculhar_bau)
                .addContainerGap(224, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Vasculhar_TendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Vasculhar_TendaActionPerformed

        String a = null;

        int r = new Random().nextInt(2+1);

        switch (r) {

            case 1:
                a = "Cajado";
                break;
            case 2:
                a = "Selo";
                break;
             default:
                a = "cajado de cristal";
        }

      

        JOptionPane.showMessageDialog(Vasculhar_Tenda, "Você achou: " + a + ". Voce andou para fora do acampamento", "\nVoce andou para fora do acampamento", JOptionPane.WARNING_MESSAGE);

        dispose();

        Jogo2 jp = new Jogo2();
        jp.setLocationRelativeTo(jp);
        jp.setVisible(true);
    }//GEN-LAST:event_Vasculhar_TendaActionPerformed

    private void Vasculhar_bauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Vasculhar_bauActionPerformed
        JOptionPane.showMessageDialog(Vasculhar_bau, "Voce abriu um bau mimico ", " \nAviso você morreu ", JOptionPane.WARNING_MESSAGE);
       Jogo8 jp = new Jogo8();
        jp.setLocationRelativeTo(jp);
        jp.setVisible(true);
           dispose();
    }//GEN-LAST:event_Vasculhar_bauActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Jogo12.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Jogo12.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Jogo12.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Jogo12.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Jogo12().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Vasculhar_Tenda;
    private javax.swing.JButton Vasculhar_bau;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
